-- ============================================================================
-- pantheon_agent_ext
-- ----------------------------------------------------------------------------
-- 1:1 extension to LobeHub-native `agents` table.
--
-- Pantheon-specific columns: runtime tier + implementation, canon/persona,
-- orchestration routing, policy gates, memory bindings, and manifest sync
-- state. Control-plane (not shell UI) is the authoritative writer; this
-- table is a cache/projection of `control-plane/manifests/agents/<slug>.yaml`.
--
-- Spec: docs/superpowers/specs/2026-04-20-pantheon-platform-architecture.md §4c / §6
-- Source of truth: control-plane manifests. This row is regenerated by
-- `pantheon project --target=shell` when the manifest changes.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "pantheon_agent_ext" (
	"agent_id" text PRIMARY KEY NOT NULL,

	-- Runtime ownership (§2.1 agent manifest → runtime.*)
	"runtime_tier" text NOT NULL DEFAULT 'pantheon',
	"runtime_implementation" text NOT NULL DEFAULT 'pantheon-py',
	"runtime_implementation_version" varchar(32),
	"fleet_path" text,
	"systemd_unit" varchar(255),
	"binary_path" text,

	-- Canon / persona (§2.1 → canon.*)
	"canon_source" varchar(64),
	"canon_character" varchar(128),
	"canon_outfit" varchar(128),
	"canon_agency" varchar(32),
	"canon_role" varchar(64),

	-- Orchestration (§2.1 → orchestration.*)
	"dispatch_position" text,
	"verify_required" boolean NOT NULL DEFAULT false,
	"phi_aware" boolean NOT NULL DEFAULT false,
	"authority_scope" boolean NOT NULL DEFAULT false,
	"receives_from" jsonb NOT NULL DEFAULT '[]'::jsonb,
	"dispatches_to" jsonb NOT NULL DEFAULT '[]'::jsonb,
	"ratifiers" jsonb NOT NULL DEFAULT '[]'::jsonb,
	"pipeline_membership" jsonb NOT NULL DEFAULT '[]'::jsonb,

	-- Policy (§2.1 → policy.*)
	"phi_guard_mode" text NOT NULL DEFAULT 'informational',
	"review_gate" boolean NOT NULL DEFAULT false,
	"max_input_tokens" integer,
	"max_output_tokens" integer,
	"allowed_platforms" jsonb NOT NULL DEFAULT '[]'::jsonb,
	"blocked_platforms" jsonb NOT NULL DEFAULT '[]'::jsonb,
	"cost_ceiling_daily_usd" numeric(10, 2),
	"policy_bundle_refs" jsonb NOT NULL DEFAULT '[]'::jsonb,

	-- Memory bindings (§2.1 → memory.*); detail rows live in
	-- pantheon_agent_memory_bindings. This column is a summary cache.
	"memory_shards" jsonb NOT NULL DEFAULT '[]'::jsonb,
	"memory_local_path" text,
	"memory_per_turn_retrieval" boolean NOT NULL DEFAULT true,
	"memory_retrieval_top_k" integer DEFAULT 5,

	-- Matrix / audit (§2.1 → matrix.*)
	"matrix_identity" varchar(255),
	"matrix_primary_room" varchar(255),
	"matrix_audit_room" varchar(255),

	-- Lifecycle (§2.1 → lifecycle.*)
	"status" text NOT NULL DEFAULT 'active',
	"manifest_version" varchar(32),
	"clinical_signoff_refs" jsonb NOT NULL DEFAULT '[]'::jsonb,

	-- Manifest sync state (control-plane ↔ cache)
	"manifest_sha" varchar(64),
	"manifest_last_synced_at" timestamp with time zone,

	"created_at" timestamp with time zone NOT NULL DEFAULT now(),
	"updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "pantheon_agent_ext" DROP CONSTRAINT IF EXISTS "pantheon_agent_ext_agent_id_agents_id_fk";--> statement-breakpoint
ALTER TABLE "pantheon_agent_ext" ADD CONSTRAINT "pantheon_agent_ext_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pantheon_agent_ext_runtime_tier_idx" ON "pantheon_agent_ext" USING btree ("runtime_tier");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pantheon_agent_ext_phi_guard_mode_idx" ON "pantheon_agent_ext" USING btree ("phi_guard_mode");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pantheon_agent_ext_status_idx" ON "pantheon_agent_ext" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pantheon_agent_ext_canon_source_idx" ON "pantheon_agent_ext" USING btree ("canon_source");
