// DO NOT EDIT BY HAND.
// Regenerate with: python3 scripts/generate-pantheon-models.py > packages/model-bank/src/aiModels/pantheon.ts
// Source of truth: /opt/obsidian-pantheon/control-plane/registry/agents.index.json
// Spec: docs/superpowers/specs/2026-04-22-gateway-design.md §D3
import type { AIChatModelCard } from '../types/aiModel';

const pantheonChatModels: AIChatModelCard[] = [
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (ade-scribe). Direct 1:1 dispatch.',
    displayName: 'Ade (Scribe)',
    enabled: true,
    id: 'pantheon-ade-scribe',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (arcana-research). Direct 1:1 dispatch.',
    displayName: 'Arcana (Research)',
    enabled: true,
    id: 'pantheon-arcana-research',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (celia-brand). Direct 1:1 dispatch.',
    displayName: 'Celia (Creative)',
    enabled: true,
    id: 'pantheon-celia-brand',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (crown). PHI-strict (clinical pipeline).',
    displayName: 'Crown (Architecture)',
    enabled: true,
    id: 'pantheon-crown',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (diana-architect). Direct 1:1 dispatch.',
    displayName: 'Diana (Architecture)',
    enabled: true,
    id: 'pantheon-diana-architect',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (dorothy-inherit). Direct 1:1 dispatch.',
    displayName: 'Dorothy (Orchestrator Classifier)',
    enabled: true,
    id: 'pantheon-dorothy-inherit',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (eclipse-verifier). Direct 1:1 dispatch.',
    displayName: 'Eclipse (Verifier)',
    enabled: true,
    id: 'pantheon-eclipse-verifier',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (enforcers). Direct 1:1 dispatch.',
    displayName: 'Enforcers (Darian + Red Hood) (Enforcer)',
    enabled: true,
    id: 'pantheon-enforcers',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (helm-aegis). Direct 1:1 dispatch.',
    displayName: 'Helm (Operations)',
    enabled: true,
    id: 'pantheon-helm-aegis',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (heretic-code). Direct 1:1 dispatch.',
    displayName: 'Scheherazade (Code)',
    enabled: true,
    id: 'pantheon-heretic-code',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (justia-valisword-lead). Direct 1:1 dispatch.',
    displayName: 'Justia (Valisword Lead)',
    enabled: true,
    id: 'pantheon-justia-valisword-lead',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (label-librarian). Direct 1:1 dispatch.',
    displayName: 'Label (Reference)',
    enabled: true,
    id: 'pantheon-label-librarian',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (liatris-creative). Direct 1:1 dispatch.',
    displayName: 'Liatris (Creative)',
    enabled: true,
    id: 'pantheon-liatris-creative',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (liliweiss-goddess-lead). Direct 1:1 dispatch.',
    displayName: 'Liliweiss (Goddess Lead)',
    enabled: true,
    id: 'pantheon-liliweiss-goddess-lead',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (loen-ethics). PHI-strict (clinical pipeline).',
    displayName: 'Loen (Ethics)',
    enabled: true,
    id: 'pantheon-loen-ethics',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (modernia-retro). Direct 1:1 dispatch.',
    displayName: 'Modernia (Reference)',
    enabled: true,
    id: 'pantheon-modernia-retro',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (morpeah-dispatcher). Direct 1:1 dispatch.',
    displayName: 'Morpeah (Operations)',
    enabled: true,
    id: 'pantheon-morpeah-dispatcher',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (nayuta-mother). Direct 1:1 dispatch.',
    displayName: 'Nayuta (Memory)',
    enabled: true,
    id: 'pantheon-nayuta-mother',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (nihilister-adversary). Direct 1:1 dispatch.',
    displayName: 'Nihilister (Adversary)',
    enabled: true,
    id: 'pantheon-nihilister-adversary',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (privaty-ops). Direct 1:1 dispatch.',
    displayName: 'Privaty (Operations)',
    enabled: true,
    id: 'pantheon-privaty-ops',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (rapi-advocate). Direct 1:1 dispatch.',
    displayName: 'Rapi (User Advocate)',
    enabled: true,
    id: 'pantheon-rapi-advocate',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (refinement-trine). Direct 1:1 dispatch.',
    displayName: 'Ludmilla (Refinement)',
    enabled: true,
    id: 'pantheon-refinement-trine',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (teresse-clinical). PHI-strict (clinical pipeline).',
    displayName: 'Teresse (Clinical)',
    enabled: true,
    id: 'pantheon-teresse-clinical',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (velvet-redteam). Direct 1:1 dispatch.',
    displayName: 'Velvet (Redteam)',
    enabled: true,
    id: 'pantheon-velvet-redteam',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (vesper-command). Direct 1:1 dispatch.',
    displayName: 'Vesper (Command)',
    enabled: true,
    id: 'pantheon-vesper-command',
    maxOutput: 8192,
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description: 'Pantheon agent (zenith-strategy). Direct 1:1 dispatch.',
    displayName: 'Zenith (Strategy)',
    enabled: true,
    id: 'pantheon-zenith-strategy',
    maxOutput: 8192,
    type: 'chat',
  },
];

export const allModels = [...pantheonChatModels];

export default allModels;
