import type { ModelProviderCard } from '@/types/llm';

/**
 * Pantheon — Direct.
 *
 * One OpenAI-compatible provider entry exposing 26 `pantheon-<slug>` models
 * (one per fleet agent). Every model is served by the Pantheon Gateway at
 * `http://host.docker.internal:18790/v1` and routed 1:1 to the target agent. PHI-strict
 * agents (Teresse, Loen, Crown) are still wrapped by the clinical pipeline
 * server-side — the "direct" label is a selection UX, not a policy bypass.
 *
 * Model list lives in `aiModels/pantheon.ts` (generated by
 * `scripts/generate-pantheon-models.py`).
 *
 * The provider is disabled by default in production builds (opt-in via
 * `NEXT_PUBLIC_PANTHEON_PROVIDERS=1`). In dev (`NODE_ENV !== 'production'`)
 * it is enabled automatically.
 *
 * Spec: docs/superpowers/specs/2026-04-22-gateway-design.md §D3.
 */

export const isPantheonProvidersEnabled = (): boolean => {
  if (typeof process === 'undefined') return false;
  // Explicit opt-in via NEXT_PUBLIC_PANTHEON_PROVIDERS always wins.
  const flag = process.env.NEXT_PUBLIC_PANTHEON_PROVIDERS;
  if (flag === '1' || flag === 'true') return true;
  if (flag === '0' || flag === 'false') return false;
  // Default: enabled in non-production, disabled in production.
  return process.env.NODE_ENV !== 'production';
};

const Pantheon: ModelProviderCard = {
  chatModels: [],
  checkModel: 'pantheon-dispatch',
  description:
    'Pantheon — Direct routes chat traffic through the Pantheon Gateway to a specific fleet agent selected by model id. 26 agents available; clinical agents stay wrapped by the PHI pipeline server-side.',
  enabled: isPantheonProvidersEnabled(),
  id: 'pantheon',
  modelList: { showModelFetcher: true },
  name: 'Pantheon — Direct',
  settings: {
    proxyUrl: {
      placeholder: 'http://host.docker.internal:18790/v1',
    },
    sdkType: 'openai',
    showModelFetcher: true,
  },
  url: 'https://github.com/obsidianstudiosX/obsidian-pantheon',
};

export default Pantheon;
